### PR TITLE
filer_http: support uploading file with offset

### PR DESCRIPTION
**Pull request by banjiaojuhao**
```bash
# upload data to "offset" position of some_file
> curl -F file=@report.js "http://localhost:8888/javascript/some_file?offset=10"
```

### CODE REVIEW

**Comment by chrislusf** [comment]
This is nice. But what are the possible use cases?

**Comment by banjiaojuhao** [comment]
> This is nice. But what are the possible use cases?

When uploading large files, user can upload one smaller block in every request, then re-upload blocks that failed to be uploaded according to file metadata.

**Comment by chrislusf** [comment]
This API seems simpler than what https://news.ycombinator.com/item?id=27019287 mentioned https://tools.ietf.org/id/draft-wright-http-partial-upload-01.html

**Comment by chrislusf** [comment]
This could be used to resume uploading a large file, or upload in chunks.

**Pull request merged**
