### PR TITLE
Fix: remove the oversized state after compaction

### PR DESCRIPTION
**Pull request by LIBA-S**
The oversized volumes can not turn to writable state even if its size is within the writable limitsa after compaction.
.
This PR abstracts a struct to record the real state of a copyset.

### CODE REVIEW

**Comment by chrislusf** [comment]
Thanks for the thoughtful PR!

I will merge this. 

Do you consider the case when a volume replication is changed? Maybe need another PR.

**Comment by chrislusf** [comment]
Reverted this PR since it is breaking test topology.TestHandlingVolumeServerHeartbeat()

**Comment by LIBA-S** [comment]
thanks, I will calibrate with caution.

> Reverted this PR since it is breaking test topology.TestHandlingVolumeServerHeartbeat()

**Comment by LIBA-S** [comment]
Hi，I have completed the unit and integration tests.  And I will give serious consideration to the issues you mentioned.

> Thanks for the thoughtful PR!
> 
> I will merge this.
> 
> Do you consider the case when a volume replication is changed? Maybe need another PR.

**Comment by chrislusf** [comment]
create a new PR

**Pull request merged**
