### PR TITLE
Rearrange S3 API methods handlers traversal

### PR DESCRIPTION
**Pull request by zerospiel**
weed/s3api: rearrange s3 methods handlers to ensure correct methods requesting

Otherwise current calls for some methods (i.e. GetObjectAcl) ends up with wrong method selection (i.e. GetObject).

Added generic comment rule of traversing methods

### CODE REVIEW

**Comment by kmlebedev** [comment]
Did s3tests pass?

https://github.com/chrislusf/seaweedfs/blob/master/docker/Makefile#L58

**Comment by zerospiel** [comment]
Uh, oh, didn't see that 😔  I'll check in a moment

**Comment by zerospiel** [comment]
@kmlebedev thanks a lot! There were 2 failed tests for multi objects deletion. Will fix it

**Comment by zerospiel** [comment]
@kmlebedev it looks like those failing tests and test suites are not working on master at least on `6bee1e9714dace680b19d5a3e8481915e3755ff5` commit (here is an external link to diffchecker https://www.diffchecker.com/0WicrhtW)

I've got an email with your comment about panic but cannot see it currently, can you please share it once again?

**Comment by kmlebedev** [comment]
> @kmlebedev it looks like those failing tests and test suites are not working on master at least on `6bee1e9714dace680b19d5a3e8481915e3755ff5` commit (here is an external link to diffchecker https://www.diffchecker.com/0WicrhtW)

@zerospiel Yes it is, test test_list_multipart_upload_owner looks suspicious

**Comment by zerospiel** [comment]
Actually, this is because of #2631 that [codes of lines](https://github.com/chrislusf/seaweedfs/pull/2631/files#diff-996424778a4e7fd909426f9273af86e72e9d9944450359def8431c28bdcdb914R47-R49)

```
func (s3a *S3ApiServer) PutBucketAclHandler(w http.ResponseWriter, r *http.Request) {
	s3err.WriteErrorResponse(w, r, s3err.ErrNotImplemented)
}
```

**Pull request merged**
