### PR TITLE
Add TiKV Filerstore back

### PR DESCRIPTION
**Pull request by blacktear23**
# What problem are we solving?

Update TiKV client version and add one PC support. After update TiKV client version the go library conflict problem is gone.

# How are we solving the problem?

Update TiKV client version.

# Checks
- [ ] I have added unit tests if possible.
- [ ] I will add related wiki document changes and link to this PR after merging.

### CODE REVIEW

**Comment by chrislusf** [comment]
how much larger the compiled version will be with and without the tikv support?
can you make it part of `make full_install` as how YDB/RocksDB works?

**Comment by blacktear23** [comment]
Run `go build` without TiKV: 73MB
Run `go build -tags "tikv"` with TiKV: 81MB
Increase 8MB.

Run `go build -ldflags "-s -w"` without TiKV: 58MB
Run `go build -ldflags "-s -w" -tags "tikv"` with TiKV: 64MB
Increase 6MB

**Comment by chrislusf** [comment]
need to add to `https://github.com/chrislusf/seaweedfs/blob/master/.github/workflows/go.yml` also

**Comment by chrislusf** [comment]
thanks! Please also adjust https://github.com/chrislusf/seaweedfs/wiki/Filer-Stores

**Comment by blacktear23** [comment]
Updated. :)

**Pull request merged**
