### PR TITLE
Proxy the master UI to the leader as well

### PR DESCRIPTION
**Pull request by Woellchen**

### CODE REVIEW

**Comment by chrislusf** [comment]
How to just see the UI of one particular master?

**Comment by Woellchen** [comment]
Ok maybe I am doing it wrong, but whenever I open the status page of a master that is not leader, the tables are all empty and i have to click on the leader link to access the status page from the leader.
I thought this was maybe overlooked because the `/` route is also proxied to the leader.
With this change I can always see a working status page no matter which master I access.

**Comment by chrislusf** [comment]
Right. But sometimes there could be problem with the non-leader master and we need to check the UI.

**Comment by Woellchen** [comment]
Ok, I am fine with that :) We can close this if you want.

**Pull request closed without merging**
