### PR TITLE
 Iam Api Server

### PR DESCRIPTION
**Pull request by kmlebedev**
Rebase and add tests https://github.com/chrislusf/seaweedfs/pull/1658

### CODE REVIEW

**Comment by kmlebedev** [comment]
@chrislusf Here is the most necessary thing and ready for merging

**Comment by chrislusf** [comment]
Merged! Thanks! Now need some wiki on how to use it properly.

**Comment by kmlebedev** [comment]
> Merged! Thanks! Now need some wiki on how to use it properly.

ok.
@chrislusf How can I get a RWlock on the file with the s3 config in the filer?

**Comment by chrislusf** [comment]
there is no lock now. The last write wins.

**Pull request merged**
