### PR TITLE
replication to todays date directory

### PR DESCRIPTION
**Pull request by kmlebedev**

### CODE REVIEW

**Comment by kmlebedev** [comment]
This is needed for an incremental backup.

**Comment by chrislusf** [comment]
on second thought, I think it is better to avoid this feature. 

1. The deletions or updates would not work.
2. The configuration is a bit hard to understand.

**Comment by kmlebedev** [comment]
> on second thought, I think it is better to remove this feature.
> 
> 1. The deletions or updates would not work.
I redo on entry mtime

**Comment by chrislusf** [comment]
How about create one sink with simple "rsync" to local, and another sink with daily partitions?

**Comment by chrislusf** [comment]
> 1. The deletions or updates would not work.
>    I redo on entry mtime

You may want to use entry ctime, which does not change for following updates after creation.

**Comment by kmlebedev** [comment]
> How about create one sink with simple "rsync" to local, and another sink with daily partitions?

You can, you need to think about how to reduce the copy-paste of the code

**Pull request merged**
