### PR TITLE
s3: check the MD5 values from clients (For multipart upload, only check the MD5 value of each part)

### PR DESCRIPTION
**Pull request by wuh-fnst**
#1894

### CODE REVIEW

**Comment by kmlebedev** [comment]
@wuh-fnst Its is checker for multipart upload ?
Since the E-tag depends on the number of chunks, and the number of chunks depends on the size of the chunk, the E-tag may differ from md5

**Comment by wuh-fnst** [comment]
@kmlebedev  I have only a limited understanding of chunks. Please tell me more if you could.
a chunk are equivalent to a part?
In multipart upload, Etag seems to be only affected by the content of r.body
When I try to upload 4GB part, it works well.

**Comment by kmlebedev** [comment]
https://yadi.sk/d/glxNn01Ll2TU8A

```
Frame 5: 668 bytes on wire (5344 bits), 668 bytes captured (5344 bits) on interface lo0, id 0
Null/Loopback
Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.1
Transmission Control Protocol, Src Port: 49330, Dst Port: 8333, Seq: 1, Ack: 1, Len: 612
Hypertext Transfer Protocol
    POST /test/test.apk?uploads HTTP/1.1\r\n
    Host: 127.0.0.1:8333\r\n
    Accept-Encoding: identity\r\n
    Content-Type: application/vnd.android.package-archive\r\n
    User-Agent: aws-cli/2.1.28 Python/3.9.2 Darwin/20.2.0 source/x86_64 prompt/off command/s3.cp\r\n
    X-Amz-Date: 20210312T094243Z\r\n
    X-Amz-Content-SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\r\n
    Authorization: AWS4-HMAC-SHA256 Credential=some_access_key1/20210312/us-east-1/s3/aws4_request, SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date, Signature=2f6d748aa43dad2133ac85888a9897b4c8f8fdbef7ca6f338ccbee051e26f067\r\n
    Content-Length: 0\r\n
    \r\n
    [Full request URI: http://127.0.0.1:8333/test/test.apk?uploads]
    [HTTP request 1/3]
    [Response in frame: 7]

```

partNumber=4
```
Hypertext Transfer Protocol
    PUT /test/test.apk?uploadId=a067e9ea-54e3-4879-896f-fa78ca515351&partNumber=4 HTTP/1.1\r\n
    Host: 127.0.0.1:8333\r\n
    Accept-Encoding: identity\r\n
    User-Agent: aws-cli/2.1.28 Python/3.9.2 Darwin/20.2.0 source/x86_64 prompt/off command/s3.cp\r\n
    Content-MD5: vmyxfySDq/nL8FyYTHBLEA==\r\n
    Expect: 100-continue\r\n
    X-Amz-Date: 20210312T094243Z\r\n
    X-Amz-Content-SHA256: 2451169d3e0f180fa6bda977cf360675eee3c28c9f69be912ba0681c5620db4c\r\n
    Authorization: AWS4-HMAC-SHA256 Credential=some_access_key1/20210312/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=926d1ce9c5211e700318338df0838383835dd016f483e957bb86b5d2ce237e1c\r\n
    Content-Length: 1570044\r\n
    \r\n
    [Full request URI: http://127.0.0.1:8333/test/test.apk?uploadId=a067e9ea-54e3-4879-896f-fa78ca515351&partNumber=4]
    [HTTP request 3/3]
    [Response in frame: 1426]
    File Data: 1570044 bytes
    Data (1570044 bytes)
```

```
Hypertext Transfer Protocol
    PUT /test/test.apk?uploadId=a067e9ea-54e3-4879-896f-fa78ca515351&partNumber=1 HTTP/1.1\r\n
    Host: 127.0.0.1:8333\r\n
    Accept-Encoding: identity\r\n
    User-Agent: aws-cli/2.1.28 Python/3.9.2 Darwin/20.2.0 source/x86_64 prompt/off command/s3.cp\r\n
    Content-MD5: WF5kTKMuu4jGL6kfLmT8DA==\r\n
    Expect: 100-continue\r\n
    X-Amz-Date: 20210312T094244Z\r\n
    X-Amz-Content-SHA256: 1e28dce8319142295fda458ab2100c29483f79d979ee145e7b6e9a96be8aef17\r\n
    Authorization: AWS4-HMAC-SHA256 Credential=some_access_key1/20210312/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=3f379e260f8325df0a98d9c5d7c330fe28e1819a89c58abd3a9dd07a56f40832\r\n
    Content-Length: 5242880\r\n
    \r\n
    [Full request URI: http://127.0.0.1:8333/test/test.apk?uploadId=a067e9ea-54e3-4879-896f-fa78ca515351&partNumber=1]
    [HTTP request 2/2]
    [Response in frame: 2761]
    File Data: 5242880 bytes
    Data (5242880 bytes)

```


```
Hypertext Transfer Protocol
    PUT /test/test.apk?uploadId=a067e9ea-54e3-4879-896f-fa78ca515351&partNumber=3 HTTP/1.1\r\n
    Host: 127.0.0.1:8333\r\n
    Accept-Encoding: identity\r\n
    User-Agent: aws-cli/2.1.28 Python/3.9.2 Darwin/20.2.0 source/x86_64 prompt/off command/s3.cp\r\n
    Content-MD5: HLccQUl1bQ0MEUPoaZ/zgg==\r\n
    Expect: 100-continue\r\n
    X-Amz-Date: 20210312T094244Z\r\n
    X-Amz-Content-SHA256: 8e7f90840783edfb64ea07a3c4c7333f44d60b2e84e4e17909a2fb348bb7ecbd\r\n
    Authorization: AWS4-HMAC-SHA256 Credential=some_access_key1/20210312/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=43bd8750858a5ea1747cd84415e1c54fed1b0939a3a1a7bf43fdad8c6ab6eeb0\r\n
    Content-Length: 5242880\r\n
    \r\n
    [Full request URI: http://127.0.0.1:8333/test/test.apk?uploadId=a067e9ea-54e3-4879-896f-fa78ca515351&partNumber=3]
    [HTTP request 2/3]
    [Response in frame: 2765]
    [Next request in frame: 2767]
    File Data: 5242880 bytes
    Data (5242880 bytes)

```


```
Hypertext Transfer Protocol
    PUT /test/test.apk?uploadId=a067e9ea-54e3-4879-896f-fa78ca515351&partNumber=2 HTTP/1.1\r\n
    Host: 127.0.0.1:8333\r\n
    Accept-Encoding: identity\r\n
    User-Agent: aws-cli/2.1.28 Python/3.9.2 Darwin/20.2.0 source/x86_64 prompt/off command/s3.cp\r\n
    Content-MD5: pshiHNhysdnPzRjqq07CMw==\r\n
    Expect: 100-continue\r\n
    X-Amz-Date: 20210312T094244Z\r\n
    X-Amz-Content-SHA256: 8d4f406c36ba1c1acd7ad0487deb8a258bd8d5cf69e2ba08c4ffe978321179a6\r\n
    Authorization: AWS4-HMAC-SHA256 Credential=some_access_key1/20210312/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=4984fa56737ff89ffdfd7e782c91b0b2e6542413c27d365b366cab317d468f12\r\n
    Content-Length: 5242880\r\n
    \r\n
    [Full request URI: http://127.0.0.1:8333/test/test.apk?uploadId=a067e9ea-54e3-4879-896f-fa78ca515351&partNumber=2]
    [HTTP request 2/2]
    [Response in frame: 2763]
    File Data: 5242880 bytes
    Data (5242880 bytes)

```

```
Hypertext Transfer Protocol
    POST /test/test.apk?uploadId=a067e9ea-54e3-4879-896f-fa78ca515351 HTTP/1.1\r\n
    Host: 127.0.0.1:8333\r\n
    Accept-Encoding: identity\r\n
    User-Agent: aws-cli/2.1.28 Python/3.9.2 Darwin/20.2.0 source/x86_64 prompt/off command/s3.cp\r\n
    X-Amz-Date: 20210312T094245Z\r\n
    X-Amz-Content-SHA256: 41e641418c176ba21bd69ded62d341f2dc21a94f31830ac226afa1cebef1dcbf\r\n
    Authorization: AWS4-HMAC-SHA256 Credential=some_access_key1/20210312/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=8942c5420dd306c954337a1eaad06d45a9b6f912dbe548bad19cfc63c6eaa7ea\r\n
    Content-Length: 443\r\n
    \r\n
    [Full request URI: http://127.0.0.1:8333/test/test.apk?uploadId=a067e9ea-54e3-4879-896f-fa78ca515351]
    [HTTP request 3/3]
    [Prev request in frame: 2710]
    [Response in frame: 2769]
    File Data: 443 bytes
    Data (443 bytes)

```
HEAD response
```
Hypertext Transfer Protocol
    HTTP/1.1 200 OK\r\n
    Accept-Ranges: bytes\r\n
    Access-Control-Expose-Headers: Content-Disposition\r\n
    Content-Disposition: inline; filename="test.apk"\r\n
    Content-Length: 17298684\r\n
    Date: Fri, 12 Mar 2021 09:48:43 GMT\r\n
    Etag: "340a5f0427635aaa0a1b6cd3f9fd11ed-4"\r\n
    Last-Modified: Fri, 12 Mar 2021 09:42:45 GMT\r\n
    Server: SeaweedFS Filer 30GB 2.31\r\n
    \r\n
    [HTTP response 1/1]
    [Time since request: 0.006269000 seconds]
    [Request in frame: 2791]
    [Request URI: http://127.0.0.1:8333/test/test.apk]

```

**Comment by kmlebedev** [comment]
@wuh-fnst It is not clear from the pull request what is being compared with what
I know that the filler store records and stores the E-tag for chunk parts  is `Etag: "585e644ca32ebb88c62fa91f2e64fc0c"` and for full multipart part file is `Etag: "340a5f0427635aaa0a1b6cd3f9fd11ed-4"`

**Comment by wuh-fnst** [comment]
@kmlebedev Yes, I noticed.
PUT partNumber=1
```
Content-MD5: WF5kTKMuu4jGL6kfLmT8DA==
```
response PUT partNumber=1
```
Etag: "585e644ca32ebb88c62fa91f2e64fc0c"
```
I think it's consistent.
```
># echo "585e644ca32ebb88c62fa91f2e64fc0c" | xxd -r -ps | base64
WF5kTKMuu4jGL6kfLmT8DA==
```

Only the MD5 value of each part is confirmed, and the MD5 value of the final file is not confirmed.

**Comment by kmlebedev** [comment]
ok

**Comment by kmlebedev** [comment]
I don't really see any sense in this, since md5 of what was actually written to disk is not checked

**Comment by wuh-fnst** [comment]
I think the client should know if the data is inconsistent. An error should be returned.
https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html

**Pull request closed without merging**
