### PR TITLE
 FEATURE: add JWT to HTTP endpoints of Filer and use them in S3 Client 

### PR DESCRIPTION
**Pull request by skurfuerst**
# Description

- one JWT for reading and one for writing, analogous to how the JWT
  between Master and Volume Server works
- I did not implement IP `whiteList` parameter on the filer

Additionally, because http_util.DownloadFile now sets the JWT,
the `download` command should now work when `jwt.signing.read` is
configured. By looking at the code, I think this case did not work
before.

## Docs to be adjusted after a release

Page `Amazon-S3-API`:

```
# Authentication with Filer

You can use mTLS for the gRPC connection between S3-API-Proxy and the filer, as
explained in [Security-Configuration](Security-Configuration) -
controlled by the `grpc.*` configuration in `security.toml`.

Starting with version XX, it is also possible to authenticate the HTTP
operations between the S3-API-Proxy and the Filer (especially
uploading new files). This is configured by setting
`jwt.jwt.filer_signing.key` and `jwt.filer_signing.read.key` in
`security.toml`.

With both configurations (gRPC and JWT), it is possible to have Filer
and S3 communicate in fully authenticated fashion; so Filer will reject
any unauthenticated communication.
```

Page `Security Overview`:

```
The following items are not covered, yet:

- master server http REST services

Starting with version XX, the Filer HTTP REST services can be secured
with a JWT, by setting `jwt.filer_signing.key` and
`jwt.filer_signing.read.key` in `security.toml`.

...

Before version XX: "weed filer -disableHttp", disable http operations, only gRPC operations are allowed. This works with "weed mount" by FUSE. It does **not work** with the [S3 Gateway](Amazon S3 API), as this does HTTP calls to the Filer.
Starting with version XX: secured by JWT, by setting `jwt.filer_signing.key` and `jwt.filer_signing.read.key` in `security.toml`. **This now works with the [S3 Gateway](Amazon S3 API).**

...

# Securing Filer HTTP with JWT

To enable JWT-based access control for the Filer,

1. generate `security.toml` file by `weed scaffold -config=security`
2. set `jwt.filer_signing.key` to a secret string - and optionally `jwt.filer_signing.read.key` as well to a secret string
3. copy the same `security.toml` file to the filers and all S3 proxies.

If `jwt.filer_signing.key` is configured: When sending upload/update/delete HTTP operations to a filer server, the request header `Authorization` should be the JWT string (`Authorization: Bearer [JwtToken]`). The operation is authorized after the filer validates the JWT with `jwt.filer_signing.key`.

If `jwt.filer_signing.read.key` is configured: When sending GET or HEAD requests to a filer server, the request header `Authorization` should be the JWT string (`Authorization: Bearer [JwtToken]`). The operation is authorized after the filer validates the JWT with `jwt.filer_signing.read.key`.

The S3 API Gateway reads the above JWT keys and sends authenticated
HTTP requests to the filer.
```

Page `Security Configuration`:

```
(update scaffold file)

...

[jwt.filer_signing]
key = "blahblahblahblah"

[jwt.filer_signing.read]
key = "blahblahblahblah"
```

Resolves: #158

### CODE REVIEW

**Comment by skurfuerst** [comment]
Hey @chrislusf,

IMHO this is ready except for testing. I'll test this in detail in the upcoming days, before it can be merged. 

I think it can be already thoroughly reviewed.

All the best, 
Sebastian

**Comment by chrislusf** [comment]
Looks good. Can you move the filer jwt checking to this separate file instead of mixing it with existing logic?

https://github.com/chrislusf/seaweedfs/blob/master/weed/server/filer_server_handlers.go

**Comment by skurfuerst** [comment]
@chrislusf good catch! Changed the code, what do you think about it?

I think I am now also securing the "proxy to volume servers" case properly - so all cases should be covered now.

As said, I'll test in detail in the upcoming days and then report back :) When this all works in practice, I think this would be ready to merge.

All the best,
Sebastian

**Comment by skurfuerst** [comment]
Hey @chrislusf during testing, I found some tiny bugs which are fixed now.

BTW: I added a script to execute a S3 conformance test suite based on https://github.com/ceph/s3-tests - to be sure that I did not break anything regarding S3 compatibility before and after this change.

IMHO this is ready to merge now :)

All the best, and a happy new year,
Sebastian

**Comment by chrislusf** [comment]
Thanks for the great work! Merged.

**Comment by chrislusf** [comment]
Please help to update the wiki also. @skurfuerst

**Comment by skurfuerst** [comment]
@chrislusf sure, planned this for today. Wiki is all updated now :)  Thanks again for your great work, it's a pleasure to work with you!

**Pull request merged**
