### PR TITLE
healthz check to avoid drain node with last replicas

### PR DESCRIPTION
**Pull request by kmlebedev**

### CODE REVIEW

**Comment by LazyDBA247-Anyvision** [comment]
@kmlebedev Hi, can the new healthz route be used as a k8s liveness check?
what will a new "empty" volume server response will be?

**Comment by kmlebedev** [comment]
> @kmlebedev Hi, can the new healthz route be used as a k8s liveness check? what will a new "empty" volume server response will be?

No you can not. i only use for startupprobe

**Comment by LazyDBA247-Anyvision** [comment]
in general /healthz route is saved for liveness (usually) 
and we sure need /healthz in volume server, running /status as an /healthz is taking too many resources.

**Comment by kmlebedev** [comment]
> in general /healthz route is saved for liveness (usually) and we sure need /healthz in volume server, running /status as an /healthz is taking too many resources.

I agree, but so far I don’t see that you can check

**Pull request merged**
