### PR TITLE
prefer to read from volumes in this data center

### PR DESCRIPTION
**Pull request by kmlebedev**
https://github.com/chrislusf/seaweedfs/issues/1608

### CODE REVIEW

**Comment by chrislusf** [comment]
this is not ready, correct?

**Comment by kmlebedev** [comment]
> this is not ready, correct?

yes it's not ready

**Comment by chrislusf** [comment]
Currently the master already knows each volume id dc/rack/node. Just need to return the dc info.

https://github.com/chrislusf/seaweedfs/blob/3a5e4769cfe383ca5a3e3d4078b5e80120763f3b/weed/server/master_server_handlers.go#L73

**Comment by kmlebedev** [comment]
@chrislusf i checked it works locally
without unnecessary grpc calls

**Pull request merged**
