### PR TITLE
add timeout when uploading content

### PR DESCRIPTION
**Pull request by guol-fnst**
https://github.com/chrislusf/seaweedfs/issues/2018

### CODE REVIEW

**Comment by chrislusf** [comment]
How to verify this? This deadline is static and not extended when there are still activities going on. This will impact all use cases.

**Comment by Tech-abm** [comment]
Hello sir
Do you have whatsapp r fb account?
Please send me link i will contact you and I urgent need your help :)

**Comment by ijunaid8989** [comment]
> Hello sir
> Do you have whatsapp r fb account?
> Please send me link i will contact you and I urgent need your help :)

You can use the slack channel, seaweedfs.slack.com as well as you can use Issue tracker to get help about any issue.

**Comment by Tech-abm** [comment]
> > Hello sir
> > Do you have whatsapp r fb account?
> > Please send me link i will contact you and I urgent need your help :)
> 
> You can use the slack channel, seaweedfs.slack.com as well as you can use Issue tracker to get help about any issue. 

No sir, i want to cython encrypt on my python code..

**Pull request closed without merging**
