### PR TITLE
Advancedtls

### PR DESCRIPTION
**Pull request by kmlebedev**
# What problem are we solving?

close connections
https://github.com/chrislusf/seaweedfs/issues/2802

# How are we solving the problem?
credential reloading
https://github.com/chrislusf/seaweedfs/issues/2802

# Checks
- [ok] I have added unit tests if possible.
- [ok] I will add related wiki document changes and link to this PR after merging.

### CODE REVIEW

**Comment by kmlebedev** [comment]
Verified via ```make dev_tls``` and and works on stage layer with duration 24h for cert Issuer
```
kubectl -n s3 describe certificates.cert-manager.io fast-cert
  Duration:  24h0m0s
  Issuer Ref:
    Kind:        ClusterIssuer
    Name:        vault-issuer
  Renew Before:  6h0m0s
  Secret Name:   fast-cert
```

**Comment by chrislusf** [comment]
After this PR, is the 10 hour max connection age still needed or not related?

**Comment by kmlebedev** [comment]
> After this PR, is the 10 hour max connection age still needed or not related?

Stell needed, for recconnet with new cert

**Comment by chrislusf** [comment]
I am not clear exactly why the re-establishing the connection is necessary.

**Comment by kmlebedev** [comment]
> I am not clear exactly why the re-establishing the connection is necessary.

Let's remove max connection age - it seems to be needed more for security reasons

https://github.com/chrislusf/seaweedfs/issues/2589#issuecomment-1166467411

**Pull request merged**
