### PR TITLE
Update store_replicate.go

### PR DESCRIPTION
**Pull request by hxiaodon**
replication operations should be equal to volume's replication setting

### CODE REVIEW

**Comment by hxiaodon** [comment]
There is a tiny mistake, I should use glog.V(0).Infof instead of glog.V(0).Infoln, if possible, please let me create another pull request.

**Comment by dgryski** [comment]
Just push another commit to your branch.  If possible, squash and/or rebase and `push -f`.

**Comment by hxiaodon** [comment]
Hi,Damian
I did not find any new push commit in chrislusf:master or my forked one(hxiaodon:master), could you explain more clearly? Thanks!

**Comment by dgryski** [comment]
More detailed instructions at http://stackoverflow.com/a/15055649

**Comment by hxiaodon** [comment]
Damian
I read the instructions you provided, but I still failed to operate at my local
image
BTW, Could you share your IM account so I can ask your help by online chatting? 
Thanks!

**Comment by hxiaodon** [comment]
Damian,
Is below operation correct?
image
Thanks!

**Comment by chrislusf** [comment]
Why not follow the easiest option in the link?

To update a pull request (point #1), the only thing you need to do is checkout the same branch the pull request is from and push to it again:

cd /my/fork
git checkout master
...
git commit -va -m "Correcting for PR comments"
git push

**Comment by hxiaodon** [comment]
I'm a little confused, Damian said that he had pushed another commit in my forked repository(github.com/hxiaodon/seaweedfs), but I did not find it .
The last commit is 
https://github.com/hxiaodon/seaweedfs/commit/4e48f64512d3f6fdbab17e777fff3fe191592a76
and parent commit is 
https://github.com/hxiaodon/seaweedfs/commit/4d56039ad4ee96db938af4df93bd4b0153c1400f
So I use Damian's suggested way(rebase) to make sure not to bring in any trouble

**Comment by chrislusf** [comment]
merged and adjusted the printout

**Pull request merged**
