### PR TITLE
made a little change for Amazon S3 API's compatibility(v2)

### PR DESCRIPTION
**Pull request by hxiaodon**
Chris
I made some refactoring work, please help to review at your available time. Feel free to give me your suggestions~
Thanks!

### CODE REVIEW

**Comment by chrislusf** [comment]
Thanks! The error handling needs more tweaking. I will add it myself.

**Comment by chrislusf** [comment]
Thanks!!!

**Comment by chrislusf** [comment]
Please comment here on how to test your use case, and how to utilize this feature.

If you know how to change the wiki, you are welcome to change it directly.

**Comment by hxiaodon** [comment]
To test this fix, we need some preparation work
1.  Read the relevant API reference, such as: [Amazon S3 object PUT API](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html) , make clear that sometimes file content will full fill the http body with no other meta info when uploading file with rest API. Many developers also develop file upload feature using this way, adapting this kind of case is necessary, I think 
2.   Write a test case is very easy, you could directly use http-util API with your favorite PL to create a http  request with following format
`
PUT /myBucket/my-image.jpg HTTP/1.1
Host: s3.amazonaws.com
Date: Wed, 12 Oct 2009 17:50:00 GMT
Authorization: authorization string
Content-Type: text/plain
Content-Length: 11434
x-amz-meta-author: Janet
Expect: 100-continue
[11434 bytes of object data]
` 
Or you could do some investigation for the existed [go s3 sdk](https://github.com/aws/aws-sdk-go/blob/master/service/s3/examples_test.go) , and make an customization and use it

Chris, please let me know if this is what you want.
Thanks!

**Pull request merged**
