### PR TITLE
security master use access.ui

### PR DESCRIPTION
**Pull request by kmlebedev**
Disable master api separately from UI

### CODE REVIEW

**Comment by chrislusf** [comment]
disable ui access is good but not really "safe", right?

**Comment by kmlebedev** [comment]
Disable ui access is safe, unlike api access. This PR allows disable api access and enable ui access is good

**Comment by chrislusf** [comment]
Got it. How about just always enable the UI access, and the "DisableHttp" only applies to API access?

I want to avoid the number of options if possible.

**Comment by kmlebedev** [comment]
> Got it. How about just always enable the UI access, and the "DisableHttp" only applies to API access?
> 
> I want to avoid the number of options if possible.

understand, let's do it

**Pull request merged**
