### PR TITLE
notification: add Go CDK pubsub support

### PR DESCRIPTION
**Pull request by jba**
Add the gocdk_pub_sub package, which supports the Go Cloud Development
Kit pubsub API.

Link in all current providers.

Update the notification scaffold.

### CODE REVIEW

**Comment by chrislusf** [comment]
Nice! There are some build errors:

'''
121.52s$ go get ./weed/...
package gocloud.dev/pubsub/awssnssqs: unrecognized import path "gocloud.dev/pubsub/awssnssqs" (parse https://gocloud.dev/pubsub/awssnssqs?go-get=1: no go-import meta tags ())
package gocloud.dev/pubsub/azuresb: unrecognized import path "gocloud.dev/pubsub/azuresb" (parse https://gocloud.dev/pubsub/azuresb?go-get=1: no go-import meta tags ())
package gocloud.dev/pubsub/natspubsub: unrecognized import path "gocloud.dev/pubsub/natspubsub" (parse https://gocloud.dev/pubsub/natspubsub?go-get=1: no go-import meta tags ())
The command "go get ./weed/..." failed and exited with 1 during .
Your build has been stopped.
'''

**Comment by chrislusf** [comment]
Not sure whether it is complicated. Can this gocloud.dev/pubsub be moved to github.com?

**Comment by chrislusf** [comment]
FYI: the build log

https://travis-ci.org/chrislusf/seaweedfs/builds/508889375

**Comment by chrislusf** [comment]
Can this gocloud.dev/pubsub be moved/cloned to github?

Seems this is not new: https://github.com/googleapis/google-cloud-go/issues/820

**Comment by jba** [comment]
I'm working on this; it is a problem with go-import redirects for the gocloud.dev import paths.

**Comment by jba** [comment]
Tests are passing now.

**Comment by chrislusf** [comment]
Thanks a lot!

Is there any way to avoid this in the future? These go import redirects seem fragile.

**Comment by jba** [comment]
> Is there any way to avoid this in the future? These go import redirects seem fragile.

We're automating our process so this won't happen again. 

More generally, the Go ecosystem will soon have proxies, which will pretty much end availability issues.  Run `go help goproxy` in Go 1.12.

**Comment by chrislusf** [comment]
@jba SeaweedFS use the notification to replicate files across systems. The current PR implemented SendMessage(). We need another one to ReceiveMessage(), similar to https://github.com/chrislusf/seaweedfs/blob/master/weed/replication/sub/notification_google_pub_sub.go#L94

Could you please also help here? Thanks!

**Comment by jba** [comment]
Sure, I'll try to get to it this week.

**Pull request merged**
