### PR TITLE
avoid connect to the old filler address

### PR DESCRIPTION
**Pull request by kmlebedev**
https://github.com/chrislusf/seaweedfs/issues/2545

### CODE REVIEW

**Comment by kmlebedev** [comment]
@chrislusf ping

**Comment by ChrisluRoblox** [comment]
Removed the counter for connected filer in 34b743c

**Comment by chrislusf** [comment]
Removed the counter for connected filer in https://github.com/chrislusf/seaweedfs/commit/34b743c481e65b25c052512603d1794eddfe839c

**Comment by chrislusf** [comment]
this particular PR is not needed.

**Pull request merged**
